language: ruby
script: >
  echo '\documentclass{article}\begin{document}Hello, world!\end{document}' | pdflatex
before_install:
  - gem update bundler
  - wget https://github.com/jgm/pandoc/releases/download/1.15.2/pandoc-1.15.2-1-amd64.deb
  - sudo dpkg -i pandoc-1.15.2-1-amd64.deb
  - rm pandoc-1.15.2-1-amd64.deb
  - sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-full
install:
  - PATH=$HOME/texlive/bin/x86_64-linux:$PATH
  - bundle install
  
  script:
  - bundle exec jekyll build
  - make
  - xelatex -interaction=nonstopmode -halt-on-error resume.tex
  

deploy:
  provider: releases
  api_key:
    secure: 
    file: article.pdf
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    repo: git-anish/cv

