name: Awesome-CI

on: [push]

jobs:
  awesome-cv-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: git-anish/cv@0.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.ok }}
      with:
        FILE_NAME: 'resume.tex'
