name: Anish-CV

on:
  push:

jobs:
  awesome-cv-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      uses: git-anish/CV
    - uses: git-anish/CV@0.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.ok }}
      with:
        FILE_NAME: 'resume.tex'
        args: -xelatex -latexoption=-file-line-error -latexoption=-interaction=nonstopmode
