name: Test Github Action
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile basic LaTeX document
        uses: ./
        with:
          root_file: resume.tex
          working_directory: ./
          args: "-xelatex -latexoption=-file-line-error -latexoption=-interaction=nonstopmode"
      - name: move to dir # Move the generated files into output folder
        run: |
          mkdir -p output
          yes| cp -rf resume.pdf ./output/
      - name: Commit files # commit the output folder
        run: |
          git config --local user.email "git-anish@github.com"
          git config --local user.name "git-anish"
          git add ./output
          git commit -m "Add changes"
          git push origin master
      - name: Push changes # push the output folder to your repo
        uses: git-anish/CV@master
        with:
          branch: master #ignore if your branch is master
          github_token: ${{ secrets.ok }}
          force: true