name: Test Github Action
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
      - uses: actions/checkout@v1
      - uses: git-anish/CV@master
      - name: Compile basic LaTeX document
        with:
          root_file: resume.tex
          working_directory: /
          args: "-xelatex -latexoption=-file-line-error -latexoption=-interaction=nonstopmode"
